PyCQA/pycodestyle

docs/intro.rst
pep8.py

Sometimes `isinstance()` is not suitable for comparing types.  For
example, someone may want to make sure an object is exact instance of a
type, not instance of its subclasses.
This patch allows to use `# noqa` comment to disable warning in this case.

allow use # noqa to disable E721 warning

---

.travis.yml

The pypy jobs have not failed in a long time. Keeping them in
allowed_failures means that if they start failing, no one will notice
them.
We also start using "sudo: false" since we are not installing anything
with apt and this will speed up build times.

Remove pypy* from allowed failures

---

.travis.yml
pep8.py
testsuite/test_api.py

This involves fixing a test and avoiding a function deprecated since Python 3.0.
https://docs.python.org/dev/library/inspect.html#inspect.getargspec

Support Python 3.5

---

pep8.py
testsuite/test_all.py
testsuite/test_parser.py

In `tox.ini` it is entirely possible to have multi-line lists with trailing commas, e.g.
```
envlist =
py27,
py34,
```
If however you do
```
[pep8]
ignore =
E1,
E2,
```
then `options.ignore` ends up as `('\nE1', \nE2', '')`
The first two items of that tuple are "mildly inconvenient"; the preceding `\n` just means the ignore is...ignored - a consequence of the multiline
The empty string as the last item, a consequence of the trailing comma, is much more insidious, as it causes all checks to be silently ignored thanks to https://github.com/PyCQA/pep8/blob/master/pep8.py#L1890-L1901, specifically
```
return (code.startswith(self.options.ignore) and
not code.startswith(self.options.select))
```
Currently, this PR includes some py27 tests to demonstrate this behaviour (I haven't tested my …

Multi-line ignore parsing in config_file

---

pep8.py

The two versions of parameter parsing were not, in fact, equivalent. The
return types of `inspect.signature` and `inspect.getargspec` are, in
fact, subtly different.
See:
* https://docs.python.org/3/library/inspect.html#inspect.signature
* https://github.com/praw-dev/praw/issues/541#issuecomment-152280322

Correct _get_parameters.

---

pep8.py

On Python 3, when python3 with run with -bb, comparison between bytes
and str raises a BytesWarning exception. Test the Python version
instead of testing '' == b''.

fix BytesWarning on Python 3

---

pep8.py

Fix problem with treating ~ operator as binary.

---

pep8.py

Previously we handled the case where binary operators were being used
as unary operators except in the case where they followed another
binary operator, e.g.,
foo = (1 +
-10 *
2 /
-5)
This change updates the check for W503 to track the previous
non-whitespace token type and token text to check if it is in fact also
a binary operator (because you should never have two binary operators in
a row).
This does not handle invalid syntax, e.g.,
foo = (bar /
/baz)
But the false-positive generated for other cases was more harmful than
not catching what will instead be caught by the interpreter.
Closes gh-484

Identify binary operators used as unary operators

---

pep8.py
testsuite/E25.py

In pull request gh-361, we allowed spaces around = for default
arguments with annotations. Python 3.5 added the async keyword for
a function definition and the allowance we made in gh-361 was failing.
This allows a function definition to start with either 'def' or
'async def' now and accommodates both cases.
Closes gh-507

Allow spaces around = in async definitions

---

README.rst

Let me know if I missed anything... 
I assume the plan is to rename `pep8.py` to `pycodestyle.py`, but if not I can revert that part of the change.

Update Readme to reflect pycodestyle name change

---

pep8.py

Purposely ignoring D102 and D203 error codes.
- D102 appears to be a bug with D102
- D203 should be ignored by default by pydocstyle)

Patched pep8 to comply with pydocstyle; Closes #228.

---

CHANGES.txt
CONTRIBUTING.rst
README.rst
docs/index.rst
docs/intro.rst
setup.py

As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

CHANGES.txt
CONTRIBUTING.rst
docs/index.rst
setup.py

Updated remaining references to pep8.readthedocs.io -> pycodestyle.readthedocs.io

Finished updating rtd links

---

docs/intro.rst
pycodestyle.py
setup.cfg
testsuite/test_api.py
testsuite/test_parser.py
testsuite/test_shell.py

This fixes issue #518, pep8 still referenced in the cli help command
As a side effect,  in setup.cfg now becomes
Also, changed the path for the config file from ~/.config/pep8 to ~/.config/pycodestyle
These feel like changes that should have come with the jump to version 2.0.0, as they are breaking,
but support for  as a name can still be added if it's desired enough

Change all references to the pep8 project to say pycodestyle

---

docs/developer.rst

Just a tiny doc update to list the correct Python versions that are currently tested in Travis.

Update Python version list in docs

---

pycodestyle.py

Neither the warnings modules, nor the two local assignments in
pycodestyle's newest check were being used. This removes them and
fixes pyflakes errors raised as a result.

Remove unused imports and assignments

---

pycodestyle.py

This also updates the Checker to update it's state for physical lines
as well as logical lines. This allows maximum_line_length to rely on
Checker state for its noqa check.
Closes #538

Update maximum_line_length to use Checker.noqa

---

pycodestyle.py
testsuite/E30.py

Fix an issue where this code will produce an E302:
```
$ cat def.py
a = None
def b():
pass
$ python pycodestyle.py def.py
def.py:3:1: E302 expected 2 blank lines, found 1
$
```
but an ```async def``` does not:
```
$ cat asyncdef.py
a = None
async def b():
pass
$ python pycodestyle.py asyncdef.py
$
```

Report E302 for blank lines before an "async def"

---

pycodestyle.py

There's no need to explicitly check for a string type when parsing the
configuration file. When it's neither an integer or a boolean, the only
value it can logically be is string-like.
Closes gh-561

Stop checking for string option type

---

CHANGES.txt

Per #573, 
I'm not exactly sure what exactly is important to you to have in the changelog.
I ran `git log 2.0.0..HEAD --oneline` on `master` and then trimmed up the following output, based on what sounded important/useful.
```
1391c7e Update CHANGES.txt for 2.1.0 release.
1e71012 Merge pull request #562 from sigmavirus24/bug/561
d4b8f49 Stop checking for string option type
0babee5 Merge pull request #557 from gitter-badger/gitter-badge
df8a6c0 Add Gitter badge
001a0ce Merge pull request #556 from markpeek/markpeek-async-def
72acd6f Report E302 for blank lines before an "async def"
4438622 Updated tox to do same tests as Travis CI
5c4c081 Removed test code unrelated to utf-8 checks
08f4891 Merge branch 'gh-536'
a0d5d5d Added test case based on @gvanrossum comment
2a5e575 Updated checker …
```

Update CHANGES.txt for 2.1.0 release.

---

pycodestyle.py

The fix used in #400 did not account for usage of "def" or "class" at the beginning of variables such as "default" or "classify". This PR looks for a space at the end of these keywords.

Fix E305 regression in 2.1.0 due to fix for #400

---

CHANGES.txt
docs/intro.rst
pycodestyle.py
testsuite/E30.py
testsuite/E40.py
testsuite/E72.py

Warn about bare except clause

---

pycodestyle.py
testsuite/E90.py
testsuite/python3.py

This is based on #611 to avoid a conflict.  I can rebase / reorder if requested.
This resolves #575

Don't report E701 for variable annotations

---

pycodestyle.py

without it `register_check()` using ERRORCODE_REGEX will not register E306 into error code list. This in effect will make `pycodestyle --select=E306` to not work.

 added function doc to blank_lines() for E306

---

.travis.yml
tox.ini

This reduces confusion about how travis runs tests versus a local
developer.
**Note** this also adds a Flake8 test env and runs it at the gate to catch other instances of https://github.com/PyCQA/pycodestyle/pull/540

Switch Travis to use tox

---

pycodestyle.py
testsuite/E30not.py

This was similar to an issue we had with E306 in which we were only
checking that a line started with "def" or "class" which catches global
vars like "defaults" or "classification".
Closes gh-617

Fix regression in E302 detection

---

testsuite/E30not.py

The bug was already fixed since it also affected E302 but this adds a
test to ensure it doesn't regress for nested definitions either.
Closes gh-619

Add regression test for nested definitions

---

pycodestyle.py
testsuite/E50.py

Correctly report E501 when the first line of a docstring is too long

---

pycodestyle.py

This allow to run python3 -m cProfile ./pycodestyle.py …. Otherwise,
as cProfile looks to wrap every functions (in a way I did not studied
in depth), the inspection of test function found no function, and no
test were run while running under cProfile, meaning that:
$ time python3 ./pycodestyle.py coefficients-148K.py
[loads and loads of errors properly reported]
real 0m4.712s
user 0m4.684s
sys  0m0.024s
$ time python3 -m cProfile ./pycodestyle.py /home/mdk/Downloads/pystyle/stats/git-clones/PmagPy/PmagPy/coefficients-148K.py
[no error reported as no check were found by inspection]
real   0m0.447s
user   0m0.436s
sys    0m0.008s
With this patch:
$ time python3 -m cProfile ./pycodestyle.py /home/mdk/Downloads/pystyle/stats/git-clones/PmagPy/PmagPy/coefficients-148K.py
[loads and loads of …

Avoid relying on inspect to list functions.

---

pycodestyle.py

Fixes https://github.com/PyCQA/pycodestyle/issues/643 for Python 3.2+.
Had to catch a "No signature found for builtin <built-in method
search of _sre.SRE_Pattern object at 0x...>" in 3.4:
In python3.4 the search was not detected as a function, now that it's
wrapped in an lru_cache it is, yet it still has no signature (it has
in 3.5+).

Fix issue #643: Optimize noqa() with an lru_cache for Python 3.2+.

---

MANIFEST.in
setup.cfg

The wheel package format supports including the license file. This is done using the `[metadata]` section in the `setup.cfg` file. For additional information on this feature, see:
https://wheel.readthedocs.io/en/stable/index.html#including-the-license-in-the-generated-wheel-file

Include license file in the generated wheel package

---

pycodestyle.py

The warning looks fairly odd:
E722 do not use bare except'
change this to
E722 do not use bare 'except'

Fix missed quoting in E722 check

---

docs/intro.rst

Previously, the line break in the source would result in
`--hang- closing` (note the space) being rendered in the HTML.

Fix space in flag name

---

pycodestyle.py

I've been having to do ```pycodestyle.StyleGuide(verbose=True, paths=['-v'])``` to achieve verbosity to the point where I can see the configuration files included such as: 
```
user configuration: /home/mjsir911/.config/pycodestyle
cli configuration: setup.cfg
```
This simply allows ```pycodestyle.StyleGuide(verbose=True)``` to display these verbosity messages.

Allow continuation of verbosity level

---

CHANGES.txt
pycodestyle.py
setup.cfg
testsuite/E12.py
testsuite/E12not.py
testsuite/W19.py
testsuite/test_all.py
testsuite/test_api.py

This flips the W503 rule to enforce line breaks before binary operators.
Related #498 
---
TODO:

Add W504 for line breaks before binary operators

---

docs/intro.rst

Cross reference changes in pull request #502 which added this new check.

Describe code W504 line break after binary operator

---

pycodestyle.py
testsuite/E25.py

Closes https://github.com/PyCQA/pycodestyle/issues/692

Add E252 on missing whitespace for annotated parameter defaults

---

CHANGES.txt
docs/intro.rst
pycodestyle.py
testsuite/W60.py

From https://docs.python.org/3/whatsnew/3.6.html#new-keywords
> async and await are not recommended to be used as variable, class, function or module names. Introduced by PEP 492 in Python 3.5, they will become proper keywords in Python 3.7. Starting in Python 3.6, the use of async or await as names will generate a DeprecationWarning.
By adding a warning to pycodestyle.py these future warnings and syntax errors can be caught during static code analysis.
The await expression tests were taken from PEP-492.
https://www.python.org/dev/peps/pep-0492/#id58

Add W606 warning for async and await keywords in Python 3.7

---

pycodestyle.py
testsuite/E25.py
testsuite/E30.py
testsuite/E70.py

Scope
=====
This started as a fix for the #728 issue, where we got a warning and tests are failing on python 3.7.
But I have retargeted for the whole python 3.7
Why we got this
============
In python 3.7 we got `async` keyword.
Changes
=======
Just explicitly escape the nested brackets. I went for escaping both the start and the end.
How to test
==========
Give it a try on Python 3.7... but I hope that Travis-CI will help with the tests.

Fix support for Python 3.7.

---

pycodestyle.py
testsuite/E50.py

Add check to avoid long line error on shebang lines (as discussed in [Issue 734](https://github.com/PyCQA/pycodestyle/issues/734)), and a test for this behaviour.

Ignore length of shebang line

---

CHANGES.txt

I have updated the changelog to reflect all the changes since the last PyPI release in order to allow master to reach a publishable state.
I tried to filter out any changes that have no end-user impact, but I was still quite liberal in what I included into the list. If there is anything which is a bit too granular I can remove it.
Thanks!

Add changelog items for 2.3.1...master

---

pycodestyle.py

test environment:
```
$ python -V
Python 3.6.5
$ pycodestyle --version
2.4.0
```
input file:
```python
regex = ('hello', "\.png$")
def main():
regex = ('hello', "\.png$")
```
before:
```
target.py:1:2: W605 invalid escape sequence '\.'
regex = ('hello', "\.png$")
^
Invalid escape sequences are deprecated in Python 3.6.
Okay: regex = r'\.png$'
W605: regex = '\.png$'
target.py:5:6: W605 invalid escape sequence '\.'
regex = ('hello', "\.png$")
^
Invalid escape sequences are deprecated in Python 3.6.
Okay: regex = r'\.png$'
W605: regex = '\.png$'
```
after:
```
target.py:1:19: W605 invalid escape sequence '\.'
regex = ('hello', "\.png$")
^
Invalid escape sequences are deprecated in Python 3.6.
Okay: regex = r'\.png$'
W605: regex = '\.png$'
target.py:5:23: W605 invalid escape sequence '\.' …
```

Change the position pointed out by W605

---

docs/intro.rst

Hi,
I updated intro.rst to explain the default configuration when using **--ignore=errors** option (see issue #685). Thank you for your reviews in advance.
Best regards,

Fix the explanation about the default configuration #685

---

pycodestyle.py

test environment:
```
$ python -V
Python 3.6.5
$ pycodestyle --version
2.4.0
$ pycodestyle --select=W --show-source target.py
```
input:
```python
var = (1 &     # comment
~2)
(width == 0 and
height == 0)
```
before:
```
target.py:1:8: W504 line break after binary operator
var = (1 &     # comment
^
target.py:3:2: W504 line break after binary operator
(width == 0 and
^
```
after:
```
target.py:1:10: W504 line break after binary operator
var = (1 &     # comment
^
target.py:3:13: W504 line break after binary operator
(width == 0 and
^
```
Thanks

Change the position pointed out by W504

---

.travis.yml
CHANGES.txt
docs/developer.rst
pycodestyle.py
setup.py
testsuite/test_api.py
tox.ini

Python 2.6 an 3.3 are end of life. They are no longer receiving bug fixes, including for security issues. Python 2.6 went EOL on 2013-10-29 and 3.3 on 2017-09-29. For additional details on support Python versions, see: https://devguide.python.org/#status-of-python-branches
Removing support for EOL Pythons will reduce testing and maintenance resources. Removed all workarounds for older Pythons.
Updated trove classifiers and documentation to better communicate supported Python versions.
Additionally, pass python_requires argument to setuptools. Helps pip decide what version of the library to install. 
https://packaging.python.org/tutorials/distributing-packages/#python-requires
> If your project only runs on certain Python versions, setting the python_requires argument to the appropriate …

Remove support for EOL Python 2.6 and 3.3

---

README.rst
docs/intro.rst

For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html

Update all pypi.python.org URLs to pypi.org

---

CONTRIBUTING.rst
docs/advanced.rst
testsuite/support.py

The nose project has ceased development. The last commit is from Mar 3, 2016. From their docs page:
https://nose.readthedocs.io/
> Note to Users
>
> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership.New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

Remove suggestion and documentation of using unmaintained nose

---

pycodestyle.py
testsuite/W60.py

Instead of having W605 point to the beginning of the string literal, make it point to the precise line and column of the invalid escape sequence.
This is more helpful when you have multiline string literals.
See #795.

Make W605 point to the invalid sequence

---

pycodestyle.py

https://github.com/python/cpython/commit/c4ef4896eac86a6759901c8546e26de4695a1389
is not yet part of any release of Python but has been backported to all
versions in Git (includeing 2.7!). It causes the tokenize.py module to
emit a synthetic NEWLINE token for files that do not in fact end with a
newline, which confuses pycodestyle's checks for blank lines at the end
of a file. Fortunately the synthetic NEWLINE tokens are easy to detect
(the token text is "").
Fixes #786

Keep compability with stdlib tokenize.py changes

---

pycodestyle.py
testsuite/W60.py

`await NUMBER` or `await STRING` is not valid syntax
@jdufresne could you help on this? If I miss some cases, I'll add NUMBER/STRING to tests

refs W606, only NAME can follow await

---

pycodestyle.py
testsuite/E10.py
testsuite/E11.py
testsuite/E90.py
testsuite/W19.py
testsuite/test_api.py
testsuite/test_shell.py

Fixes #836
@sciyoshi Are you able to test if this fixes the issue you reported?

Expect lines to be indented 8 places when tabs are used

---

pycodestyle.py

Closes https://github.com/PyCQA/pycodestyle/pull/707
Closes #700

Fixes some issues with E741 detection

---

pycodestyle.py
testsuite/E30.py

Fix E302 false negative in presence of decorators.

---

pycodestyle.py
testsuite/python3.py

Ellipsis is not a binary operator

---

pycodestyle.py
testsuite/E40.py

E402: Add "with" statement to allowed keywords

---

.travis.yml
pycodestyle.py
testsuite/python38.py
tox.ini

Introduced in Python 3.8 with PEP-572. Refer to https://www.python.org/dev/peps/pep-0572.
I took some tests from the PEP's examples section.
Closes #865.
(Really not a fan of binary operators before line breaks.)

Add support for assignment expressions

---

pycodestyle.py
testsuite/E22.py

Closes https://github.com/PyCQA/pycodestyle/issues/768

Adds matmul operator support, fixes #768

---

.gitignore
CONTRIBUTING.rst

Had noticed this while doing #834.

CONTRIBUTING: Make virtualenv dir name consistent with gitignore

---

pycodestyle.py
testsuite/E12.py
testsuite/E12not.py

"with" is likely the most common case, and this indentation is
explicitly given as example by PEP8 (under "maximum line length").
Closes #569.

Support visual indent of continuation lines after with/assert/raise.

---

pycodestyle.py
testsuite/E30not.py

Previously
```
def oneliner(): pass
def otheroneliner(): pass
def really_long_func():
with_some_contents
```
would raise an "E302: expected 2 blank lines, found zero" at the last
line of the one liner.  Ultimately, this is due to `expand_indent` being
passed a line whose contents are just a newline and nothing else, and
`expand_indent` thinking that the line is indented by 1 character (the
newline), which is wrong.
Fix that by just stripping the newline, and modify a test to cover this
case.

Correctly allow *two* blank lines after a block of one-liners.

---

pycodestyle.py
testsuite/E30not.py

re-allow decorated one-liners

---

pycodestyle.py
testsuite/E71.py

E714: fix chained `is not`

---

README.rst
docs/index.rst
setup.py

The project documentation seems to have changed location. There were still a few URLs pointing to the old one.

Update documentation URLs to pycodestyle.pycqa.org

---

pycodestyle.py
testsuite/W29.py
testsuite/W39.py

fix skipping of physical checks when file does not end in newline

---

testsuite/test_shell.py
testsuite/test_util.py

Fix tests to handle paths in Windows.  NormalizePath works properly but the tests would still fail because NormalizePath would NOT work as the test results expected.  Verified on Windows with command:  `/mingw64/bin/python -m unittest discover testsuite -v`
Results:
`D:\msys64\home\jpmugaas\pycodestyle/pycodestyle.py:124:30: W504 line break after binary operator
D:\msys64\home\jpmugaas\pycodestyle/pycodestyle.py:125:35: W504 line break after binary operator
D:\msys64\home\jpmugaas\pycodestyle/pycodestyle.py:298:46: W504 line break after binary operator
D:\msys64\home\jpmugaas\pycodestyle/pycodestyle.py:394:41: W504 line break after binary operator
D:\msys64\home\jpmugaas\pycodestyle/pycodestyle.py:401:75: W504ok
test_selftest (test_all.PycodestyleTestCase) ... ok
test_check_nullbytes …

Windows path issues

---

.github/workflows/main.yml
pycodestyle.py
testsuite/python310.py
testsuite/support.py

Fix false-positive `E211 whitespace before '('` for `match` and `case`, Python 3.10

Fix false-positive E211 with match and case

---

pycodestyle.py

Small issue I missed for #989. Technically this isn't a problem since even the alpha versions are `> (3, 10)`
/CC: @asottile

Small fix to version_info comparison

---

pycodestyle.py
testsuite/python310.py
testsuite/support.py
tox.ini

`E271 multiple spaces after keyword` and `E275 missing whitespace after keyword` should also also be emitted for `match` and `case`. However, since they are only soft keywords, some additional logic is needed.
If accepted and the next version is released, this check could be added to flake8 as well ([flake8/setup.cfg](https://github.com/PyCQA/flake8/blob/7a371265cf876736b8d03907df26b813874b4201/setup.cfg#L72-L74)).

Add whitespace checks for ``match`` and ``case``

---

pycodestyle.py

- despite `re.compile(...)` being cached, this still amounts to 60% of the
overhead of the `bare_except` check
- overall, this improved pycodestyle performance by about .25% (.0025)

improve performance of bare_except check

---

pycodestyle.py

in profiles, this attributed somewhere between 4% and 14% of pycodestyle's execution time
this is committed upstream in cpython 3.10, I've also used this to get pretty significant performance boosts in my formatter tools which are based on [tokenize-rt](https://github.com/asottile/tokenize-rt/blob/6911895baaf8e8c309c112d43e54f58a1f17efdd/tokenize_rt.py#L16-L22)

add performance hack to improve tokenize speed

---

pycodestyle.py
testsuite/python38.py

Following #867 and #918.
I was going to make a bug report, but it looked easy enough to propose a fix instead 🙂

Fix E225 for lambdas with all positional-only arguments

---

pycodestyle.py
testsuite/E20.py

```
printf 'foo(\tbar)\n' | pycodestyle -
stdin:1:5: E201 whitespace after '('
```
Fixes #588

Issue #588: E201: detect tabs as whitespace

---

pycodestyle.py
testsuite/E72.py
testsuite/custom_types.py

tl;dr [The PEP8 example for the issue][0] only includes the `type(a) == type(b)` comparison, it does not include the `== types.SomeType` issue, the latter should not be handled under this error check.
This check was introduced to trunk following issue #47, and I believe it _incorrectly_ borrowed the example from the issue literally. The E721 check was since reported on a few false-positive issues and then expanded a number of times to handle those around types (see 034b9f4fb082f72e1087a8a27dd0dd61486d1888 and 0327e55e756e20ade468e67992f9f43da14aabb4).
I believe the behaviour should change because object comparison cannot be confirmed a "type comparison" in the same sense; not without having additional information, which is not possible with regex alone (_maybe_ with AST analysis).
This …

fix E721 types regex

---

pycodestyle.py

this improves performance by about 1%
best of 10 (running `python3 -m pycodestyle pycodestyle.py pycodestyle.py pycodestyle.py pycodestyle.py pycodestyle.py`
- before: 2.501s
- after: 2.435s

use short-circuit evaluation in _is_binary_operator

---

docs/intro.rst

The double-dash for command line option `--ignore` was being converted to an en-dash.
I'm not very familiar with RST, but this change seems correct. By all means reject if not.
Same change as PyCQA/pydocstyle/pull/579

docs: Fix double-dash converted to en-dash

---

pycodestyle.py
testsuite/E12not.py
testsuite/E27.py
testsuite/W19.py

The error message was worded to cover more cases, so I just reused E275 here; I can also add a new error code instead if you prefer.
Partially addresses #371 (only the "space required after keyword" part, not the "space required before keyword" part).

Generalize E275 to require space after all keywords, not just "import".

---

pycodestyle.py

Closes https://github.com/PyCQA/pycodestyle/issues/934
Am I missing some place that we may want `, ]` instead of `,]`?

E231 should work with tuples in brackets

---

README.rst
docs/intro.rst
pycodestyle.py
testsuite/W60.py

Closes https://github.com/PyCQA/pycodestyle/issues/1107

Delete W601 -> W604 warnings

---

pycodestyle.py

Closes https://github.com/PyCQA/pycodestyle/issues/959
Closes https://github.com/PyCQA/pycodestyle/issues/935

E741 should work with lambdas

---

pycodestyle.py
testsuite/python36.py

this still does not pass the full testsuite -- but this gets closer to that

add fix for muting FSTRING_MIDDLE in 3.12+

---

pycodestyle.py
testsuite/E72.py

see #1084 and #1041 for more details
resolves #1084 
resolves #830

allow `is` and `is not` for type comparisons (E721)

---

tox.ini

planning to make the self tests easier to run / more repeatable without needing the whole testsuite run
going to remove most of the custom testsuite code we have and use pytest parameterization instead

run testsuite with pytest

---

pycodestyle.py
testing/data/E50.py

this was double-reporting E501 above the fstring in 3.12

3.12: fix fstring starting with escape

---

testing/data/E30.py

Add two test cases to verify that pycodestyle correctly flags 2 empty lines in non-toplevel contexts, even outside of functions: one for two empty lines between class methods and one for two empty lines in the indented body of an `if:` statement at toplevel.
The motivation here is to resolve ambiguity about the intended behaviour of this rule.  See https://github.com/astral-sh/ruff/pull/8720#issuecomment-1817837253.

testing: add a pair of E303 testcases

---

pycodestyle.py

unlikely that anyone would ever hit this in reality -- `'== type(' + ' ' * 4096 + '\t' * 4096`

improve backtracking of COMPARE_TYPE_REGEX

---

pycodestyle.py
testing/data/E72.py

E721 was reported on the result of member functions of name "type" with one parameter, if those occurred on the left side of an equality operator comparison.

prevent false positive for E721 on member function

---

pycodestyle.py
testing/data/E50.py

Since the comment flag was being set and then never disabled in the `explicit_line_join` implementation, any redundant backslash which occured after the first comment in a logical line would go undetected. e.g.
```
y = (
2 + 2  # \
+ 3  # \
+ 4 \
+ 3
)
```
would not detect the redundant backslash after the 4.

E502: Fix E502 being disabled after a comment in a logical line

---

pycodestyle.py
tests/test_pycodestyle.py

adjust logical line for FSTRING_MIDDLE brace escaping

---

pycodestyle.py

This provides a small speed-up on large codebases (~80ms).
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
12900025    2.590    0.000    2.590    0.000 {method 'append' of 'list' objects}
```
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `pycodestyle .` | 18.178 ± 0.198 | 17.951 | 18.666 | 1.00 |
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
4457822    1.049    0.000    1.049    0.000 {method 'append' of 'list' objects}
```
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `pycodestyle .` | 18.099 ± 0.132 | 17.887 | 18.346 | 1.00 |
I profiled pycodestyle with the yt-dlp codebase because it is similar in composition to a private codebase I have.
```shell
git clone …
```

Use list comprehensions to avoid append() calls

---

pycodestyle.py

This provides a small speed-up on large codebases (~90ms).
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1609756    0.432    0.000    0.432    0.000 {method 'rstrip' of 'str' objects}
```
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `pycodestyle .` | 18.178 ± 0.198 | 17.951 | 18.666 | 1.00 |
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1137564    0.311    0.000    0.311    0.000 {method 'rstrip' of 'str' objects}
```
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `pycodestyle .` | 18.090 ± 0.155 | 17.784 | 18.264 | 1.00 |
I profiled pycodestyle with the yt-dlp codebase because it is similar in composition to a private codebase I have.
```shell
git clone …
```

Combine rstrip calls in trailing_whitespace check

---

pycodestyle.py
testing/data/python313.py
tests/test_E901.py

add support for PEP 696 generic defaults

---

pycodestyle.py

[Benchmarks](https://github.com/PyCQA/pycodestyle/pull/1290#issue-3225528348)

reduce "python_3000_invalid_escape_sequence" execution time by ~60%

---

pycodestyle.py

[Benchmarks](https://github.com/PyCQA/pycodestyle/pull/1290#issue-3225528348)

reduce "missing_whitespace_after_keyword" execution time by ~17%
