PyCQA/pycodestyle

README.rst
I guess this repository got moved at some point?
=> Point to new GitHub URL

pep8.py
This updates the PR with the suggested code review and rebases it so that it is mergeable
=> Update PR #409

.travis.yml
Add a notification for the PyCQA channel
=> Add python 3.5 support

CONTRIBUTING.rst, docs/developer.rst
Because I've seen these come up a few times in PR discussions etc., but couldn't find explicit written reference for them in any of the documentation
=> Documentation of high-level goals/aims/decisions

CHANGES.txt, pep8.py
New pull request following from #469 discussion
=> v1.7 release

CHANGES.txt, pep8.py, testsuite/test_api.py
These misspellings were found using [mwic](http://jwilk.net/software/mwic).
=> Fix spelling

setup.py
Minor change to update the fields configured in setup.py for the package metadata.
=> Added maintainer metadata to package

CONTRIBUTING.rst
Hello!
I noticed from #521, that you guys were looking for something like this to cut the next release.
Let me know if there is anything you want to change or add!
=> Add contributing instructions.

pycodestyle.py
Towards https://github.com/PyCQA/pycodestyle/issues/573.
This is options 1 and 2 I think that were mentioned there.
Support for both `[pep8]` and `[pycodestyle]` in config/ini. There is also a warning generated mentioning the deprecation of the `[pep8]` section.
=> Check for both [pep8] and [pycodestyle] config sections.

pycodestyle.py, testsuite/E40.py
Closes #394 
Rebased from #523
=> Allow all dunder variables above imports

pycodestyle.py
As the offsets looks already sorted (which looks logical so I assumed
they always are), using a bisection if faster than iterating over all
of them.
On a "worst case scenario" I encontered, I got nice enhancement with this patch:
$ time python3 ./pycodestyle.py ~/Downloads/PmagPy/PmagPy/coefficients-552K.py > /dev/null
real 1m16.405s
$ time python3 ./pycodestyle.py ~/Downloads/PmagPy/PmagPy/coefficients-552K.py > /dev/null
real 0m3.318s
=> Use bisect instead of iterating over every offsets.

pycodestyle.py, testsuite/python3.py
This is an extension of #634, but with passing tests.
=> Fix variable annotations

docs/intro.rst
Patch for https://github.com/PyCQA/pycodestyle/issues/666
Tests:
- All tests pass
=> Add examples

docs/developer.rst
=> Add Python 3.6 to test list in dev docs

pycodestyle.py, testsuite/test_shell.py
=> Fix handling of diffs with mnemonic prefixes

.travis.yml, setup.py, tox.ini
Python 3.7 was released on June 27, 2018.
https://docs.python.org/3/whatsnew/3.7.html
=> Add testing and document support for Python 3.7

pycodestyle.py, testsuite/E30.py, testsuite/E30not.py
=> Allow omitting blank lines around one-liner definitions.

tox.ini
The previous one lead to a dead-end 404.
=> Update tox url in tox.ini

pycodestyle.py, testsuite/E72.py
=> Fix E721 false positive

pycodestyle.py, testsuite/E30.py, testsuite/E30not.py, testsuite/test_blank_lines.py
=> Allow N-and-fewer blank lines before the first top level thing

pycodestyle.py, testsuite/python38.py
=> Fix E225 for PEP 570 all positional-only arguments

.coveragerc, .gitignore, testsuite/test_all.py, testsuite/test_api.py, tox.ini
this makes it more clear which parts are covered / uncovered such that we can improve the testsuite to cover them
=> Instrument code coverage

setup.py
Background info at
https://github.com/pypa/warehouse/pull/7882#issue-412444446
=> Add Changes project URL

setup.py
Follow up to comments to 8e7b671
=> Remove broken mention of testsuite from setup.py

.github/workflows/main.yml, CONTRIBUTING.rst, README.rst, docs/developer.rst, setup.py
github actions no longer supports python 3.4
=> drop python 3.4

pycodestyle.py, testsuite/E71.py
=> detect multiple E712 in a line

pycodestyle.py, testsuite/python38.py
=> Allow __all__ to be typed

pycodestyle.py, testsuite/python310.py
Similar to #989: add ignore for soft keywords.
Closes #1002
=> Fix false-positive with star pattern

pycodestyle.py, testsuite/E27.py, testsuite/python3.py, testsuite/python310.py
This reverts commit 0f079a061590217515421fc337df8dbf3563fed5, reversing
changes made to 3d0ac73d8045b5fa771dbbf594ca0b9a4e581e15.
resolves #1024
=> revert #990

.github/workflows/main.yml, .pre-commit-config.yaml, docs/conf.py, pycodestyle.py, setup.py, tox.ini
not worth trying to fight python 2 stuff in #1035 -- let's just drop it!
=> drop support for python 2.x

pycodestyle.py, testsuite/E72.py
=> fix regex bug for E721

pycodestyle.py, testsuite/E27.py
=> fix IndexError regression with E275

pycodestyle.py, testsuite/E72.py
This reverts commit 8b5c964321776b2fe8dfd25f4f18db0ffbdbd281, reversing
changes made to 9777ac5a8ea1ae14e70bfb27063e2e7c0daa06e3.
See #1084 for details
=> Revert "Merge pull request #1041 from asfaltboy/issue-830-e721-types-regex-incorrect"

pycodestyle.py, testsuite/E27.py
=> allow parenthesized yield (generator-coroutines)

docs/intro.rst
=> make the example ignore a valid prefix

pycodestyle.py, testsuite/E74.py, testsuite/python38.py
=> fix reporting of ambiguous identifier after parameter list

.github/workflows/main.yml, .pre-commit-config.yaml, setup.py, testsuite/test_api.py, tox.ini
github actions no longer supports it
=> drop python3.6

testsuite/support.py, testsuite/test_blank_lines.py
splitting this out to make version-specific error handling easier for 3.12
=> make testsuite helper for generating errors

pycodestyle.py, testsuite/E22.py, testsuite/test_E901.py
this slightly simplifies some checking
=> combine whitespace around operator checks

pycodestyle.py, testsuite/E12.py
super minor -- but makes it easier to do my regression diffing
=> make E231 offsets match pycodestyle 2.10

pycodestyle.py, testing/data/python36.py
=> fix 3.12 false positive when fstring chunk is a keyword
